version: '3.8'
services:
  bot:
    # Uncomment the following line to build the bot locally and comment out the image line
    build: .
    container_name: random-mute-bot
    env_file: .env
    depends_on:
      - mongo
    restart: unless-stopped
  mongo:
    image: mongo:latest
    container_name: bot-db
    env_file: .env
    volumes:
      - ./mongo-data:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped